/*
 * partition_wal_header.h
 * On-disk record layout for pg_parwal segment files.
 *
 * Every record in a pg_parwal/<partition_id>/<segname> file begins with a
 * PartWALHeader.  PartWALSkip is the variable-length extension used when
 * WalSender marks a gap in the global LSN stream.
 */
#ifndef PARTITION_WAL_HEADER_H
#define PARTITION_WAL_HEADER_H

#include "postgres.h"
#include "access/xlogdefs.h"

/* ------------------------------------------------------------------ */
/* Magic and flags                                                      */
/* ------------------------------------------------------------------ */

#define PARTWAL_MAGIC        UINT32_C(0x50415254)   /* "PART" */

/* PartWALHeader.flags bit values */
#define PARTWAL_FLAG_DATA        UINT8_C(0x01)  /* regular partition data record */
#define PARTWAL_FLAG_SKIP        UINT8_C(0x02)  /* WalSender gap marker          */
#define PARTWAL_FLAG_CHECKPOINT  UINT8_C(0x04)  /* checkpoint boundary marker    */

/* ------------------------------------------------------------------ */
/* Core header — embedded in every pg_parwal record                     */
/* ------------------------------------------------------------------ */

/*
 * PartWALHeader
 *
 * orig_node_lsn:  global physical LSN generated by the primary node that
 *                 produced this write.  Guarantees global uniqueness and
 *                 is the anchor for crash recovery on the primary.
 *
 * partition_lsn:  per-partition strictly-monotone counter (starts at 1).
 *                 Replica sync and integrity checks depend exclusively on
 *                 this sequence — a gap here indicates a missing record.
 */
typedef struct PartWALHeader
{
    uint32      magic;          /* PARTWAL_MAGIC — file-format guard            */
    Oid         partition_id;   /* which partition this record belongs to        */
    XLogRecPtr  orig_node_lsn;  /* global physical LSN, primary-generated        */
    uint64      partition_lsn;  /* per-partition monotone sequence (1-based)     */
    uint8       flags;          /* PARTWAL_FLAG_* bitmask                        */
} PartWALHeader;

/* ------------------------------------------------------------------ */
/* Skip record — marks gaps in the global LSN stream                    */
/* ------------------------------------------------------------------ */

/*
 * PartWALSkip
 *
 * Sent by WalSender when a global LSN range does not belong to the target
 * partition.  The receiving replica advances its local global-LSN pointer
 * to lsn_end without waiting for the missing data, keeping replication
 * non-blocking.
 *
 * header.flags must include PARTWAL_FLAG_SKIP.
 * lsn_end is exclusive (first LSN *after* the skipped range).
 */
typedef struct PartWALSkip
{
    PartWALHeader header;
    XLogRecPtr    lsn_start;    /* first global LSN of the skipped range  */
    XLogRecPtr    lsn_end;      /* first global LSN after the skipped range */
} PartWALSkip;

#endif /* PARTITION_WAL_HEADER_H */
